### ISSUE TITLE
Pressing q kills buffer but doesn't close window 

### ISSUE THREAD

**Issue by tmalsburg** [agzam/mw-thesaurus.el#14]
Using mw-thesaurus from MELPA and a somewhat outdated development build of Emacs: `GNU Emacs 26.1.91 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2019-02-01`

Super useful package.  Thanks for sharing it!

**Comment by soulawaker** [comment]
Same with me. I'm using Spacemacs v.0.300.0. And I got mw-thesaurus from this Github repository.

**Comment by agzam** [comment]
Can you guys tell me what does it say when in mw-thesaurus buffer you press `C-h k q`? For me it reports 
```
q runs the command mw-thesaurus--quit (found in mw-thesaurus-mode-map), which is
an interactive compiled Lisp function in ‘mw-thesaurus.el’.
```

evil sometimes works in mysterious ways (in both: in theology and in Emacs 😄). You may have to do something like:

```
(define-key mw-thesaurus-mode-map [remap evil-record-macro] #'mw-thesaurus--quit)
``` 

in your config.

**Comment by soulawaker** [comment]
In Spacemacs, it seems that the priority of minor mode keymaps is lower than any evil mode keymaps in accordance with [spacemacs keymaps guide](https://github.com/syl20bnr/spacemacs/wiki/Keymaps-guide). I'm using `evil-normal-state-local-map` to apply `mw-thesaurus--quit like below. It is not exactly same as one that I really use but very quite similar. I think it will work.

```emacs-lisp
(add-hook 'mw-thesaurus-mode-hook (lambda () (define-key evil-normal-state-local-map (kbd "q") 'mw-thesaurus--quit)))
```

**Comment by tmalsburg** [comment]
The window is now being closed as expected.  I guess restarting Emacs after installing mw-thesaurus did the trick, but not sure.  As as I'm concerned, this issue can be closed.
