### ISSUE TITLE
Set evil mode (if present) to insert mode when opening  `* Merriam-Webster Thesaurus *` window

### ISSUE THREAD

**Issue by tmalsburg** [agzam/mw-thesaurus.el#15]
Otherwise pressing `q` doesn't close the window.

**Comment by agzam** [comment]
This is certainly not the case for me. When you are in mw-thesaurus buffer, press `C-h k q`, what does it say? For me it says:
```
q runs the command mw-thesaurus--quit (found in mw-thesaurus-mode-map), which is
an interactive compiled Lisp function in ‘mw-thesaurus.el’.
```

**Comment by soulawaker** [comment]
@tmalsburg It seems that the priority of keymaps is the point. I suggested my code snippet on #14.

**Comment by tmalsburg** [comment]
It's working now.  No idea why.  Perhaps I had to restart Emacs? Sorry for the noisy and thanks for the response.
