### ISSUE TITLE
Word lookup without reference to point

### ISSUE THREAD

**Issue by termitereform** [agzam/mw-thesaurus.el#16]
I love this package -- but I often want to look up words without reference to the buffer I'm working on, so I modified the `mw-thesaurus-lookup-at-point` to create an alternate version that I can invoke anywhere:

```
(defun mw-thesaurus-lookup-general ()
  "Prompt for word to look up using Merriam-Webster online dictionary."
  (interactive)
  (let* ((word (read-string "Find Synonym For: "))
         (url (concat (symbol-value 'mw-thesaurus--base-url)
                      word "?key="
                      (symbol-value 'mw-thesaurus--api-key))))
    (request url
             :parser (lambda () (xml-parse-region (point-min) (point-max)))
             :success (cl-function
                       (lambda (&key data &allow-other-keys)
                         (mw-thesaurus--create-buffer word data))))))
```

**Comment by agzam** [comment]
Yes, I rarely do need that myself, but when I do, I end up opening scratch buffer, typing the word there, get angry because that feels dumb. I'll add this feature one of these days. Thank you for the suggestion.
