### ISSUE TITLE
A way to configure the thesaurus buffer

### ISSUE THREAD

**Issue by opensource-philosophy** [agzam/mw-thesaurus.el#19]
Is there a way to define how the thesaurus buffer is being shown? At the moment, it is shown at the bottom, but I would like to have it on the right, taking up about 25% of the framewidth. Calling `(split-window-right -25)` and then the respective `mw-thesaurus` function works, but is cumbersome. Any ideas?

**Comment by agzam** [comment]
This is an excerpt from my personal config:

```
(add-to-list
   'display-buffer-alist
   `(,mw-thesaurus-buffer-name
     (display-buffer-reuse-window
      display-buffer-in-direction)
     (direction . right)
     (window . root)
     (window-width . 0.3)))
 ```
 
 If that works for you, and you think someone else could find this helpful - maybe we should add this to the readme?

**Comment by opensource-philosophy** [comment]
This is great, thank you! I think it really is worth adding to the readme. What would be even better, though, would be if the buffer was not selected so you could just press `C-x 1` (`delete-other-windows`) and terminate it. This could be useful for workflow because you could lookup a word really quick and then get back to your writing with one key combination!
