### ISSUE TITLE
Getting "error in process sentinel: Before first headline at position 1 in buffer * Merriam-Webster Thesaurus *" error

### ISSUE THREAD

**Issue by todisorder** [agzam/mw-thesaurus.el#21]
Hi, I'm getting the error
`error in process sentinel: Before first headline at position 1 in buffer * Merriam-Webster Thesaurus *`
after installing mw-thesaurus with `M-x package-install` and running any of the `mw-` commands. I know this is not a lot of information, but I don't know what could be the source of the problem. I have not done any customization. Do you have any idea of what could be wrong? Thank you!

**Comment by agzam** [comment]
Can you please `M-x toggle-debug-on-error` and report the stacktrace. Most likely this has nothing to do with the package.

**Comment by todisorder** [comment]
I'm sorry for wasting your time, it suddenly started working. I still don't know what was wrong, must have been something else in my config file. Thanky for your time and for the great package!

**Comment by agzam** [comment]
No worries. I'm glad it's working.
