### ISSUE TITLE
There is no mw-thesaurus/lookup-at-point command

### ISSUE THREAD

**Issue by xuchunyang** [agzam/mw-thesaurus.el#8]
The readme says there is such command, maybe you mean `mw-thesaurus--lookup-at-point`? However, `--` is used for private function and variable, I suggest `mw-thesaurus-lookup-at-point`. And you should add autoload cookie to the command. By the way, `mw-thesaurus-mode` shouldn't be autoload, since user won't use it.

**Comment by agzam** [comment]
Thank you, fixed in master.
